# Generated by Django 4.0 on 2021-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CALL', 'Call'), ('ENTERTAINMENT', 'Entertainment'), ('ERRAND', 'Errand'), ('HOUSEWORK', 'Housework'), ('NATURE', 'Nature'), ('OUTING', 'Outing'), ('SHOPPING', 'Shopping')], default='APPOINTMENT', max_length=15)),
            ],
        ),
    ]
