# Generated by Django 4.1.2 on 2022-10-22 16:27

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("circles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT", "Appointment"),
                            ("CALL", "Call"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("ERRAND", "Errand"),
                            ("HOUSEWORK", "Housework"),
                            ("NATURE", "Nature"),
                            ("OUTING", "Outing"),
                            ("SHOPPING", "Shopping"),
                        ],
                        default="APPOINTMENT",
                        max_length=15,
                    ),
                ),
                ("activity_date", models.DateField(default=datetime.date.today)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optionally, add a brief note. For privacy, avoid adding sensitive information.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "circle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="circles.circle",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="activities", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "ordering": ["activity_date"],
            },
        ),
    ]
