# Generated by Django 4.0.1 on 2022-01-23 17:26

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_alter_companion_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CALL', 'Call'), ('ENTERTAINMENT', 'Entertainment'), ('ERRAND', 'Errand'), ('HOUSEWORK', 'Housework'), ('NATURE', 'Nature'), ('OUTING', 'Outing'), ('SHOPPING', 'Shopping')], default='APPOINTMENT', max_length=15)),
                ('activity_date', models.DateField(default=datetime.date.today)),
                ('participants', models.ManyToManyField(related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='people.person')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['activity_date'],
            },
        ),
    ]
