# Generated by Django 4.0 on 2021-12-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_groups', '0002_caregroup_members'),
        ('activities', '0002_alter_activity_options_activity_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='care_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='care_groups.caregroup'),
        ),
    ]
