# Generated by Django 4.0 on 2021-12-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_care_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['activity_date'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
    ]
