# Generated by Django 4.0.1 on 2022-01-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('activities', '0006_activity_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='care_group',
        ),
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='people.person'),
        ),
    ]
