# Generated by Django 4.0 on 2021-12-27 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregroup',
            name='members',
            field=models.ManyToManyField(related_name='care_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
