# Generated by Django 4.0 on 2022-01-04 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_groups', '0003_caregroup_coordinators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregroup',
            name='members',
            field=models.ManyToManyField(related_name='care_groups_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
