# Generated by Django 4.0 on 2022-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_groups', '0004_alter_caregroup_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregroup',
            name='coordinators',
        ),
        migrations.RemoveField(
            model_name='caregroup',
            name='members',
        ),
    ]
