# Generated by Django 4.0 on 2022-01-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_display_name_alter_user_email'),
        ('care_groups', '0006_caregroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_group_memberships', to='accounts.user'),
        ),
    ]
