# Generated by Django 4.0.1 on 2022-07-11 19:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(help_text='The region in which the locality is, and which is in the country. For example, California or another appropriate first-level Administrative division', max_length=255)),
                ('locality', models.CharField(help_text='The locality in which the street address is, and which is in the region. For example, Mountain View.', max_length=255)),
            ],
        ),
    ]
