# Generated by Django 4.0.1 on 2022-07-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_caregiverlocality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaregiverLocality',
        ),
    ]
