# Generated by Django 4.0 on 2022-01-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Anonymous', help_text='Helps other team members recognise you, such as by your given name or nickname.', max_length=15, verbose_name='display name'),
        ),
    ]
