# Generated by Django 4.0.1 on 2022-01-23 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companion',
            unique_together={('person', 'user')},
        ),
    ]
